version: "3.7"
services:
  control:
    build:
      context: ./control
      args:
        - control_port=9908
        - control_token=token
    container_name: ca_control
    ports:
      - "0.0.0.0:9908:9908"
    volumes:
      - /var/log/ca_control:/go/src/control/log
  web:
    build:
      context: ./web
      args:
        - web_port=8000
    container_name: ca_web
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - /var/log/ca_web:/go/src/web/log
  db:
    image: postgres
    container_name: ca_db
    environment:
      POSTGRES_DB: "catarchive"
      POSTGRES_USER: "catarchive"
      POSTGRES_PASSWORD: ${CA_DB_PASS}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /var/lib/postgresql/ca_db_data:/var/lib/postgresql/data
