name: Go build and format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Go formatter
        uses: sladyn98/auto-go-format@v0.0.1
        
      - name: Go build
        run: |
          cd server/control
          go build
